# W2_Multiple Linear Regression (I)


In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
train_data = pd.read_csv('kc_house_train_data.csv')
test_data = pd.read_csv('kc_house_test_data.csv')

In [3]:
train_data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [15]:
# create new features
train_data['bedrooms_squared'] = train_data['bedrooms'] * train_data['bedrooms']
train_data['bed_bath'] = train_data['bedrooms'] * train_data['bathrooms']
train_data['log_living'] = np.log(train_data['sqft_living'])
train_data['lat_long'] = train_data['lat'] + train_data['long']
test_data['bedrooms_squared'] = test_data['bedrooms'] * test_data['bedrooms']
test_data['bed_bath'] = test_data['bedrooms'] * test_data['bathrooms']
test_data['log_living'] = np.log(test_data['sqft_living'])
test_data['lat_long'] = test_data['lat'] + test_data['long']

In [16]:
# compute the average values of new features
print(round(test_data['bedrooms_squared'].mean(),2))
print(round(test_data['bed_bath'].mean(),2))
print(round(test_data['log_living'].mean(),2))
print(round(test_data['lat_long'].mean(),2))

12.45
7.5
7.55
-74.65


In [6]:
# model 1
model_1_features = train_data[['sqft_living','bedrooms','bathrooms','lat','long']]
model_1 = LinearRegression().fit(model_1_features, train_data['price'])
model_1.coef_

array([  3.12258646e+02,  -5.95865332e+04,   1.57067421e+04,
         6.58619264e+05,  -3.09374351e+05])

In [7]:
# model 2
model_2_features = train_data[['sqft_living','bedrooms','bathrooms','lat','long', 'bed_bath']]
model_2 = LinearRegression().fit(model_2_features, train_data['price'])
model_2.coef_

array([  3.06610053e+02,  -1.13446368e+05,  -7.14613083e+04,
         6.54844630e+05,  -2.94298969e+05,   2.55796520e+04])

In [8]:
# model 3
model_3_features = train_data[['sqft_living','bedrooms','bathrooms','lat','long', 'bedrooms_squared', 'bed_bath', 'log_living', 'lat_long']]
model_3 = LinearRegression().fit(model_3_features, train_data['price'])
model_3.coef_

array([  5.29422820e+02,   3.45142296e+04,   6.70607813e+04,
         5.34085611e+05,  -4.06750711e+05,  -6.78858667e+03,
        -8.57050439e+03,  -5.61831484e+05,   1.27334900e+05])

In [9]:
# function to get RSS
def get_RSS(X, model, y):
    predictions = model.predict(X)
    return sum((predictions-y) ** 2)

In [10]:
# compute RSS for each model using training data
print(get_RSS(model_1_features, model_1, train_data['price']))
print(get_RSS(model_2_features, model_2, train_data['price']))
print(get_RSS(model_3_features, model_3, train_data['price']))

9.6787996305e+14
9.58419635074e+14
9.0343645505e+14


In [11]:
# compute RSS for each model using test data
model_1_test = test_data[['sqft_living','bedrooms','bathrooms','lat','long']]
model_2_test = test_data[['sqft_living','bedrooms','bathrooms','lat','long', 'bed_bath']]
model_3_test = test_data[['sqft_living','bedrooms','bathrooms','lat','long', 'bedrooms_squared', 'bed_bath', 'log_living', 'lat_long']]
print(get_RSS(model_1_test, model_1, test_data['price']))
print(get_RSS(model_2_test, model_2, test_data['price']))
print(get_RSS(model_3_test, model_3, test_data['price']))

2.25500469795e+14
2.23377462976e+14
2.59236319207e+14
